build: fix github action result aggregation

diff --git a/.github/workflows/release-next.yaml b/.github/workflows/release-next.yaml
--- a/.github/workflows/release-next.yaml
+++ b/.github/workflows/release-next.yaml
@@ -30,34 +30,33 @@ jobs:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
           REPOSITORY: ${{ github.repository }}
         run: |
-          LAST_RELEASE_TAG=$(gh --repo "${REPOSITORY}" release list --limit 1 --json tagName | jq -r '.[0].tagName' || echo "")
-          if [[ -n "$LAST_RELEASE_TAG" ]]; then
+          LAST_RELEASE_TAG=$(gh --repo "${REPOSITORY}" release list --limit 1 --json tagName | jq -r '.[0].tagName')
+          if [[ "$LAST_RELEASE_TAG" != "null" ]]; then
             PREVIOUS_TAG_SHA=$(gh api "repos/${REPOSITORY}/git/ref/tags/${LAST_RELEASE_TAG}" --jq '.object.sha')
             echo "PREVIOUS_TAG_SHA=${PREVIOUS_TAG_SHA}" | tee -a "$GITHUB_ENV"
-            echo "CHECKOUT_REF=${PREVIOUS_TAG_SHA}" | tee -a "$GITHUB_ENV
-          else
-            REPO_CREATED_AT=$(gh api "repos/${REPOSITORY}" --jq '.created_at')
-            echo "REPO_CREATED_AT=${REPO_CREATED_AT}" | tee -a "$GITHUB_ENV"
-          fi
 
-          if [[ -z "$PREVIOUS_TAG_SHA" ]] && [[ -z "$REPO_CREATED_AT" ]]; then
-            echo >&2 "Failed to identify last release commit or repository creation date"
-            exit 1
+            if [[ -z "$PREVIOUS_TAG_SHA" ]]; then
+              echo >&2 "Failed to identify last release commit"
+              exit 1
+            fi
+          else
+            RELEASE_VERSION="v0.0.0"
+            echo "RELEASE_VERSION=${RELEASE_VERSION}" | tee -a "$GITHUB_ENV"
           fi
 
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          fetch-depth: ${{ env.REPO_CREATED_AT != '' && 0 || 50 }}
-          fetch-tags: ${{ env.PREVIOUS_TAG_SHA != '' && 'true' || 'false' }}
+          fetch-depth: ${{ env.RELEASE_VERSION != '' && 50 || 1 }}
+          fetch-tags: ${{ env.RELEASE_VERSION != '' && true || false }}
           token: ${{ steps.app-token.outputs.token }}
 
       - name: Check changed files since previous release
         uses: tj-actions/changed-files@v45
         id: changed-files
+        if: ${{ env.RELEASE_VERSION == '' }}
         with:
           base_sha: ${{ env.PREVIOUS_TAG_SHA }}
-          since: ${{ env.REPO_CREATED_AT }}
           files_yaml: |
             source_code:
               lib/**
@@ -66,22 +65,24 @@ jobs:
 
       - name: Check if a new release would be required
         env:
+          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
           CHANGED_FILES: ${{ steps.changed-files.outputs.source_code_any_changed }}
           DELETED_FILES: ${{ steps.changed-files.outputs.source_code_any_deleted }}
           MODIFIED_FILES: ${{ steps.changed-files.outputs.source_code_any_modified }}
         run: |
           PUBLISH_RELEASE=false
-          if [[ "$CHANGED_FILES" == "true" ]] || \
-             [[ "$DELETED_FILES" == "true" ]] || \
-             [[ "$MODIFIED_FILES" == "true" ]]; then
-            PUBLISH_RELEASE=true
+          if [[ -n "$RELEASE_VERSION" ]] || \
+               [[ "$CHANGED_FILES" == "true" ]] || \
+               [[ "$DELETED_FILES" == "true" ]] || \
+               [[ "$MODIFIED_FILES" == "true" ]]; then
+             PUBLISH_RELEASE=true
           fi
           echo "PUBLISH_RELEASE=${PUBLISH_RELEASE}" | tee -a "$GITHUB_ENV"
 
       - name: Generate next release version
         uses: jveldboom/action-conventional-versioning@v1
         id: version
-        if: ${{ env.PUBLISH_RELEASE == 'true' }}
+        if: ${{ env.PUBLISH_RELEASE == 'true' && env.RELEASE_VERSION == '' }}
         with:
           github-token: ${{ steps.app-token.outputs.token }}
           ignore-drafts: true
@@ -89,6 +90,12 @@ jobs:
 
       - name: Push new tag
         if: ${{ env.PUBLISH_RELEASE == 'true' }}
+        env:
+          RELEASE_VERSION: ${{ env.RELEASE_VERSION != '' && env.RELEASE_VERSION || steps.version.outputs.version-with-prefix }}
+          USER_NAME: ${{ github.actor || 'github-actions' }}
+          USER_EMAIL: ${{ github.actor || 'github-actions' }}@users.noreply.github.com
         run: |
-          git tag -a "${{ steps.version.outputs.version-with-prefix }}" -m "Release ${{ steps.version.outputs.version-with-prefix }}"
-          git push origin "${{ steps.version.outputs.version-with-prefix }}"
+          git config --local user.name "${USER_NAME}"
+          git config --local user.email "${USER_EMAIL}"
+          git tag -a "${RELEASE_VERSION}" -m "Release ${RELEASE_VERSION}"
+          git push origin "${RELEASE_VERSION}"
